#!/usr/bin/env python

QB = "Aaron Rodgers"
first_quarter = 0
second_quarter = 3
third_quarter = 14
fourth_quarter = 0

print("The QB of the Packers is %s and the first half score was %s. The final score is %s." %(QB,first_quarter+second_quarter,first_quarter+second_quarter+third_quarter+fourth_quarter)) #QB,first_quarter+second_quarter+third_quarter+fourth_quarter))
#and the Packer\'s score in tonight\'s game is %s.
